# Generated by Django 4.2 on 2023-07-13 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='end_date',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='start_date',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)]),
        ),
    ]
