# Generated by Django 4.2 on 2023-07-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Work_experience',
            new_name='WorkExperience',
        ),
    ]
