# Generated by Django 4.2 on 2023-07-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_photo_rename_work_experience_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='portfolio/'),
        ),
    ]
