# Generated by Django 4.2 on 2023-07-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_service_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
