# Generated by Django 4.2 on 2023-07-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_remove_personalinfo_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='phone',
        ),
    ]
