# Generated by Django 4.2 on 2023-07-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_remove_personalinfo_age_remove_personalinfo_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
