# Generated by Django 4.2 on 2023-07-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField()),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
