# Generated by Django 4.2 on 2023-07-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='href',
            field=models.CharField(max_length=100),
        ),
    ]
