# Generated by Django 4.2 on 2023-07-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_alter_navbar_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='icon_name',
            new_name='section_name',
        ),
    ]
