# Generated by Django 4.2 on 2023-07-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_personalinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='birthday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='quote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
