# Generated by Django 4.2 on 2023-07-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_personalinfo_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
