# Generated by Django 4.2 on 2023-07-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_personalinfo_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
